### ISSUE TITLE
Failure of download-windows.sh script

### ISSUE THREAD

**Issue by brendanhoar** [crazyqube/qvm-create-windows-qube#1]
```
[user@windows-mgmt qvm-create-windows-qube]$ ./download-windows.sh
Download Windows ISO...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3167M  100 3167M    0     0  1550k      0  0:34:51  0:34:51 --:--:-- 1954k
sha256sum: 7601.24214.180801-1700.win7sp1_ldr_escrow_CLIENT_ULTIMATE_x64FRE_en-us.iso: No such file or directory
7601.24214.180801-1700.win7sp1_ldr_escrow_CLIENT_ULTIMATE_x64FRE_en-us.iso: FAILED open or read
Win7_Pro_SP1_English_x64.iso: OK
sha256sum: WARNING: 1 listed file could not be read
Downlading update packages...
./download-windows.sh: line 19: cd: auto-tools/auto-tools/updates/windows-7/updates: No such file or directory
[user@windows-mgmt qvm-create-windows-qube]$ ls
README.md  auto-tools  download-windows.sh  install-dependencies.sh  media-creation  modules  qubes-windows-tools  qvm-create-windows-qube.sh
[user@windows-mgmt qvm-create-windows-qube]$ tree|grep iso
│   └── isos
│       └── Win7_Pro_SP1_English_x64.iso
│   └── unpack-qwt-iso.sh
[user@windows-mgmt qvm-create-windows-qube]$
```

**Comment by one7two99** [comment]
Same for me, trying the follwing steps:

# create a new AppVM
qvm-create --class AppVM --template fedora-30 --label black windows-mgmt

# Increase storage capacity
qvm-volume extend windows-mgmt:private 20480M

# Install Git in the AppVM (will be gone on next reboot)
qvm-run --auto --pass-io --no-gui --user root windows-mgmt 'dnf install -y git'

# Clone repository of qvm-create-windows-qube
qvm-run --auto --pass-io --no-gui windows-mgmt 'cd Documents && git clone https://github.com/crazyqube/qvm-create-windows-qube'

# Run the script to download all files
qvm-run --auto --pass-io --no-gui windows-mgmt 'cd Documents/qvm-create-windows-qube && ./download-windows.sh'

After this download I get the folliowing error message:

> qvm-run --auto --pass-io --no-gui windows-mgmt 'cd Documents/qvm-create-windows-qube && ./download-windows.sh'
> Download Windows ISO...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100 3167M  100 3167M    0     0  1887k      0  0:28:37  0:28:37 --:--:-- 1642kq/
> sha256sum: 7601.24214.180801-1700.win7sp1_ldr_escrow_CLIENT_ULTIMATE_x64FRE_en-us.iso7601.24214.180801-1700.win7sp1_ldr_escrow_CLIENT_ULTIMATE_x64FRE_en-us.iso: FAILED open or read
> : No such file or directory
> Win7_Pro_SP1_English_x64.iso: OK
> sha256sum: WARNING: 1 listed file could not be read
> Downlading update packages...
> ./download-windows.sh: line 19: cd: auto-tools/auto-tools/updates/windows-7/updates: No such file or directory
> 

[799]
