### ISSUE TITLE
Provision Chocolatey

### ISSUE THREAD

**Issue by Yethal** [crazyqube/qvm-create-windows-qube#2]
Chocolatey is a Windows package manager that allows for automated and unattended software deployment. Provisioning it after Windows installation would greatly increase usability (as it would allow software installation via qvm-run from another qube) and would simplify Firefox deployment.
https://chocolatey.org/

**Comment by crazyqube** [comment]
Thanks @Yethal, sounds like a good idea! I will add this to the todo list and perhaps work on it soon.

**Comment by crazyqube** [comment]
Only concern though is if somebody wanted to air-gap the Windows qube and have some packages installed by Chocolatey perhaps such as Notepad++ and Process Explorer then they wouldn't be able to without connecting that Windows qube to the internet.

Perhaps we could still allow for an air-gapped Windows qube by downloading the packages in a DispVM and then including them in Auto Tools to be installed locally if that is possible. Of course, making windows-mgmt connected to the internet is also unwanted hence the DispVM.

**Comment by crazyqube** [comment]
On second thought, after doing the following Google search:
https://www.google.com/search?q=is+chocolatey+good
It would seem people aren't all that positive about chocolatey with many people claiming that security and package maintenance is a big issue.

Top Results:
https://medium.com/@keivan/why-chocolatey-is-broken-beyond-any-hope-d1a4e33b3d23
https://www.reddit.com/r/sysadmin/comments/26ou7h/is_chocolatey_reliable_for_use/

As Qubes users, security is our number one priority and if Chocolatey is going to be any exception to that then I don't think we should implement it.

I will have to re-think this decision. We could just add it as a module for installing more packages along with the Firefox module if it's desired, however, more research is required.

**Comment by Yethal** [comment]
Both of the linked articles are five years old and do not necessarily reflect the state of Chocolatey as it is now.
Here's documentation on Chocolatey's security model:
https://chocolatey.org/docs/security

**Comment by crazyqube** [comment]
Fantastic, glad to see there's been improvements! I plan to start work on this feature very soon as it's actually something that would help me a lot in my workflow as well.

**Comment by crazyqube** [comment]
This feature has made it into master. Hopefully, you will be able to run your Windows qubes with packages isolated behind Tor soon too: https://github.com/chocolatey/chocolatey.org/issues/687
