### ISSUE TITLE
Memory balooning should be disabled by default.

### ISSUE THREAD

**Issue by brendanhoar** [crazyqube/qvm-create-windows-qube#5]
While the qubes memory manager is supposedly compatible with Windows 7 when Qubes Windows Tools is successfully installed, I find it to be unstable.

The current scripts only "de facto" disable this service (by setting initial/max memory  to the same value). However, the service is still running, and if a user mistakenly assumes that changing the Initial RAM value will force the Max to follow they will be quite surprised when the VM later dies when it cannot allocate the RAM it needs from Xen.

I propose adding, right before setting the memory values:
  qvm-service "${current_name}" meminfo-writer off

As noted in the qvm-service docs, meminfo-writer does not show up in the list of services that qvm-service displays. However, qvm-service can be used to enable and disable the service.

Brendan

**Comment by crazyqube** [comment]
From this commit it would seem that meminfo-writer will truly not exist in Qubes 4.1:
https://github.com/marmarek/qubes-core-admin/commit/fe75fc5323426beedf514840ac5da2373c0138f3

Currently, setting it would appear simply sets the maxmem to zero and so instead I've changed this line:
`qvm-prefs "$current_name" maxmem 0`
This also has the effect of graying out the option in Qubes Manager.

More info: https://github.com/QubesOS/qubes-issues/issues/4480

**Comment by brendanhoar** [comment]
Yup. Thanks!

As per just posted qubes-issue, the meminfo-writer appears to be gone and
has been replaced by some fix ups in the qubes settings and qvm-preferences
code...but apparently the fixup was missed in qvm-clone (which is not
utilized here anyway).

**Comment by brendanhoar** [comment]
Might be worth keeping an eye on this for resolution: https://github.com/QubesOS/qubes-issues/issues/5306 

From my experience, it appears it is still possible to end up with memory ballooning enabled with the checkbox unchecked. I think your setup script does not trigger this bug, but if I clone a windows VM created by your script, sometimes it ends up enabled in the way described in the qubes issue.
