### ISSUE TITLE
Script has errors init

### ISSUE THREAD

**Issue by zS3mNH2** [crazyqube/qvm-create-windows-qube#6]
You can see the following line:

`qvm-run -p "$resources_vm" "cat '$resources_dir/qvm-create-windows-qube.sh' > qvm-create-windows-qube.sh"`

See the quotes? The effect of the script is it just copies itself to itself. The quote should be moved if the intention is to put the script into dom0

**Comment by crazyqube** [comment]
Fixed in 5ea20907cb83de4aa5a6a11b84010cf0c59f0a4f.

Also, please see new location of repo for the latest updates:
https://github.com/elliotkillick/qvm-create-windows-qube
