### ISSUE TITLE
Cant run chmod the file

### ISSUE THREAD

**Issue by firstabor** [crazyqube/qvm-create-windows-qube#7]
It was a hard way to get here most of the readme mislead me but together with the qubes copy to dom0 doc i could get it through but now when i try to use 

in dom0 Terminal
chmod +x install-qvm-create-windows-qube.sh && ./install-qvm-create-windows-qube.sh

i only get following error got empty response from qubesd. see journalctl in dom0 for details

this is in journalctl

Oct 31 20:05:32 dom0 sudo[22546]:     user : TTY=pts/4 ; PWD=/home/user ; USER=root ; COMMAND=/bin/chmod +x install-qvm-create-windows-q
Oct 31 20:05:32 dom0 kernel: audit: type=1123 audit(1572566732.630:240): pid=22546 uid=1000 auid=1000 ses=2 msg='cwd="/home/user" cmd=63
Oct 31 20:05:32 dom0 kernel: audit: type=1110 audit(1572566732.630:241): pid=22546 uid=0 auid=1000 ses=2 msg='op=PAM:setcred grantors=pa
Oct 31 20:05:32 dom0 audit[22546]: USER_CMD pid=22546 uid=1000 auid=1000 ses=2 msg='cwd="/home/user" cmd=63686D6F64202B7820696E7374616C6
Oct 31 20:05:32 dom0 audit[22546]: CRED_REFR pid=22546 uid=0 auid=1000 ses=2 msg='op=PAM:setcred grantors=pam_env,pam_unix acct="root" e
Oct 31 20:05:32 dom0 sudo[22546]: pam_systemd(sudo:session): Cannot create session: Already running in a session
Oct 31 20:05:32 dom0 sudo[22546]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 31 20:05:32 dom0 kernel: audit: type=1105 audit(1572566732.633:242): pid=22546 uid=0 auid=1000 ses=2 msg='op=PAM:session_open granto
Oct 31 20:05:32 dom0 audit[22546]: USER_START pid=22546 uid=0 auid=1000 ses=2 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,p
Oct 31 20:05:32 dom0 sudo[22546]: pam_unix(sudo:session): session closed for user root
Oct 31 20:05:32 dom0 audit[22546]: USER_END pid=22546 uid=0 auid=1000 ses=2 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pa
Oct 31 20:05:32 dom0 audit[22546]: CRED_DISP pid=22546 uid=0 auid=1000 ses=2 msg='op=PAM:setcred grantors=pam_env,pam_unix acct="root" e
Oct 31 20:05:32 dom0 kernel: audit: type=1106 audit(1572566732.638:243): pid=22546 uid=0 auid=1000 ses=2 msg='op=PAM:session_close grant
Oct 31 20:05:32 dom0 kernel: audit: type=1104 audit(1572566732.638:244): pid=22546 uid=0 auid=1000 ses=2 msg='op=PAM:setcred grantors=pa
Oct 31 20:05:32 dom0 qubesd[15566]: permission denied for call b'admin.vm.Create.AppVM'+b'fedora-30' (b'dom0' → b'dom0') with payload of
~
~

**Comment by cab404** [comment]
#8 fixes it

**Comment by crazyqube** [comment]
Please try again with the latest version:
https://github.com/elliotkillick/qvm-create-windows-qube
